### ISSUE TITLE
`Observer` and `Endorser` should be able to point to different peers

### ISSUE THREAD

**Issue by guoger** [guoger/stupid#36]

**Comment by SamYuan1990** [comment]
For me understanding, this issue allow user able to given observer and endorser by their needs.
but for endorsers should meet the channel config by user them self.
As endorser policy is org1 & org2, so user should given at least two peers meets logic "org1&org2"?

plan list:
1) refactor peer and orderer node to json schema
```
Peer: {
"name":{
"socket":"address:port",
"tls":"path_to_tls_cert" 
}
},
Orderer: [
{
"socket":"address:port",
"tls":"path_to_tls_cert" 
}
],
Observer: ["name of peer",],
"Endorser": ["name of peer"]
```

**Comment by guoger** [comment]
LGTM, although this config schema might be simpler if we switch to `yaml`...

**Comment by SamYuan1990** [comment]
@guoger , close this one as completed?
