### ISSUE TITLE
Make use of `client int` in `Proposer`

### ISSUE THREAD

**Issue by guoger** [guoger/stupid#40]
We have `client_per_conn` in `config.yaml`, which is passed as `client int` in `Proposer`:
https://github.com/guoger/stupid/blob/6b3b46f98c82c860f4bec8af76606478977b3ed2/infra/proposer.go#L16

However, this is not used. Effectively, we have **one** client per connection. We should make use of it (or delete it?)

**Comment by guoger** [comment]
cc @SamYuan1990

**Comment by SamYuan1990** [comment]
https://github.com/guoger/stupid/blob/6b3b46f98c82c860f4bec8af76606478977b3ed2/infra/proposer.go#L31

so, may I know the usage here?

**Comment by guoger** [comment]
the plan was to multiplexing the *same* connection with *multiple* clients

**Comment by SamYuan1990** [comment]
also other things we are going to discuss in a nits pr maybe from #37 
we could also put 2 yamls into a directory, e.g. configs
```
s/orderers/orderer/g
(singular vs plural)
```
etc...

**Comment by SamYuan1990** [comment]
> the plan was to multiplexing the **same** connection with **multiple** clients

https://github.com/guoger/stupid/blob/6b3b46f98c82c860f4bec8af76606478977b3ed2/infra/proposer.go#L31

so the line above I showed, see how we using client's int in proposer.

**Comment by guoger** [comment]
> > the plan was to multiplexing the **same** connection with **multiple** clients
> 
> https://github.com/guoger/stupid/blob/6b3b46f98c82c860f4bec8af76606478977b3ed2/infra/proposer.go#L31
> 
> so the line above I showed, see how we using client's int in proposer.

**Comment by SamYuan1990** [comment]
https://github.com/guoger/stupid/blob/111820f84bcd3a11d85ea54250b6bbc27f2eef3e/pkg/infra/proposer.go#L48
making this as a 	
```e      chan(peer.EndorserClient) with length i?```
