### ISSUE TITLE
When I run ./stupid config.yaml 40000, there has runtime error

### ISSUE THREAD

**Issue by Daose1997** [guoger/stupid#41]
[root@localhost stupid-master]# ./stupid config.yaml 40000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9aab4f]

goroutine 347 [running]:
github.com/guoger/stupid/infra.(*Observer).Start(0xc000471c60, 0x9c40, 0xbfc015d1df916d85, 0x5cda83d, 0x109e1e0)
	/root/stupid-master/infra/observer.go:50 +0x2df
created by main.main
	/root/stupid-master/main.go:60 +0x660

**Comment by guoger** [comment]
peer那边有错误信息吗？这里的错误应该是peer返回了非成功的response

**Comment by Daose1997** [comment]
这个我当时没有细看，后面我部署test-network的时候，替换到了当时我对chaincode配置理解出了点问题，后面用回了test-network的链码之后没有问题，应该是我配置的问题

**Comment by guoger** [comment]
> 这个我当时没有细看，后面我部署test-network的时候，替换到了当时我对chaincode配置理解出了点问题，后面用回了test-network的链码之后没有问题，应该是我配置的问题

好的，那我就close了
